import Head from 'next/head';
import CommentModal from '../components/CommentModal';
import Feed from '../components/Feed';
import Sidebar from '../components/Sidebar';
import Widgets from '../components/Widgets';

export default function Home({ newsResult, userRandomResults }) {
   return (
      <div>
         <Head>
            <title>Twitter Guess</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
         </Head>

         <main className='flex min-h-screen mx-auto'>
            {/* Sidebar */}
            <Sidebar />

            {/* Feed */}
            <Feed />

            {/* Widgets */}
            <Widgets newsResult={newsResult.articles} userRandomResults={userRandomResults.results} />

            {/* Modal */}
            <CommentModal />
         </main>
      </div>
   );
}

export const getServerSideProps = async (context) => {
   // Whats happening section
   const newsResult = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/business/us.json').then(
      (res) => res.json()
   );

   // Who to follow section
   const userRandomResults = await fetch('https://randomuser.me/api/?results=30&inc=name,login,picture').then(
      (res) => res.json()
   );

   return {
      props: {
         newsResult,
         userRandomResults,
      },
   };
};
